use_frameworks!

target 'PodLib2_Example' do
  pod 'PodLib2', :path => '../'

  target 'PodLib2_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
